### ISSUE TITLE
Query Google Maps API to calculate driving/cycling/walking distance and time between points

### ISSUE THREAD

**Issue by johannesmols** [johannesmols/Caelicus#33]

**Comment by jaschn** [comment]
@johannesmols can you enable the google maps distance matrix api for the api key? https://console.cloud.google.com/google/maps-apis/api-list

**Comment by johannesmols** [comment]
Done 👍

**Comment by jaschn** [comment]
Unfortunately still fails: "API keys with referer restrictions cannot be used with this API."

**Comment by johannesmols** [comment]
Ah sorry I enabled it but didn't activate it for the key. Please try again.

**Comment by jaschn** [comment]
Still the same 🙃  I think its because you restricted the key itself to only work from localhost and github pages and thats not possible for this api

**Comment by johannesmols** [comment]
Where are you querying the API from if it isn't localhost then? There is no intermediate server or anything?

**Comment by jaschn** [comment]
Oh sorry, i made a mistake and used the server side api instead of the client side.

**Comment by johannesmols** [comment]
No worries, glad that you figured it out :)

**Comment by jaschn** [comment]
JS interop now mostly working

**Comment by johannesmols** [comment]
Discussion in #38
